name: its_live_tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10
  - rioxarray
  - geopandas
  - jupyterlab
  - scipy
  - gdal 
  - h5py
  - pyproj
  - scikit-image
  - scikit-learn
  - s3fs
  - dask
  - pip:
    - ipympl
    - zarr
    - h5netcdf
    - netcdf4
    - tqdm
    - pint
    - cvxopt
    - geoviews
    - hvplot
    - zarr
